#!/bin/bash

# Example deploy script for grasscms w/lighttpd. Crappy, but I dont ha
# ve time for more now.
# This probably works only on debian with git-core and lighttpd installed.
# Oh, and python-setuptools python-pip

setup_lighty(){
	mkdir /var/www/grasscms.com/
	cp doc/examples/grasscms.fcgi /var/www/grasscms.com
	cp doc/examples/lighttpd_grasscms.conf /etc/lighttpd/conf-enabled/
	echo "create database grasscms"| mysql -uroot -proot  
	git clone https://github.com/XayOn/GrassCMS/grasscms/static
	cp -r grasscms/static /var/www/grasscms.com/
	chown -R www-data:www-data /var/www/grasscms.com
	invoke-lighttpd restart
}

apt-get install git-core lighttpd python-pip python-setuptools

git remote -v show |grep GrassCMS && {
	git pull origin master # Github based deploy
	[[ $1 == "init_lighttpd" ]] && setup_lighty
	cd /var/www/grasscms.com/static
	git pull origin master
	cd -
} || {
	git clone https://github.com/XayOn/GrassCMS 
	cd GrassCMS
	pip install -r deps
	[[ $1 == "init_lighttpd" ]] && setup_lighty
}

python setup.py install
